import { IDepartment } from './configuration';

export interface IOperator {
  // id:number;
  // employeeId: number;
  // organizationId: number;
  // departmentId: number;
  // authorizedId: number;
  // expiryLicenseDate: string;
  // isEmployeeStatusActive: boolean;
  // profilePictureId: number;
  // firstName: string;
  // lastName: string;
  // email: string[];
  // phoneNumber: string[];
  // sendNotificationBySMS: boolean;
  // sendNotificationByEmail: boolean;
  // sendNotificationByWhatsapp: boolean;

  id: number;
  employeeNumber: number;
  firstName: string;
  lastName: string;
  profileDocId: number;
  organizationId: number;
  department: IDepartment;
  emails: string[];
  phoneNumbers: string[];
  isActive: boolean;
  roleId: number;
  role: { roleId: number; roleName: string };
  roleName: string;
  notifyByEmail: boolean;
  notifyByPush: boolean;
  notifyByCall: boolean;
  notifyBySMS: boolean;
  notifyByWhatsApp: boolean;
  vehicleComments;
  serviceEntryComment: boolean;
  fuelEntryComments: boolean;
  vehicleStatusChanges: boolean;
  voidedFuelEntries: boolean;
  dueSoonInspections: boolean;
  overdueInspections: boolean;
  newFaults: boolean;
  newRecalls: boolean;
  notifyByNewIssueEmail: boolean;
  notifyByNewIssuePush: boolean;
  notifyByIssueAssignedEmail: boolean;
  notifyByIssueAssignedPush: boolean;
  notifyByCommentOnIssueEmail: boolean;
  notifyByCommentOnIssuePush: boolean;
  notifyByIssueResolvedEmail: boolean;
  notifyByIssueResolvedPush: boolean;
  notifyByIssueCloseEmail: boolean;
  notifyByIssueClosePush: boolean;
}
