// Generated by https://quicktype.io

export interface IOrganization {
  id?: number;
  numOfLocations?:number;
  numOfDepartments?:number;
  organizationNumber: number;
  organizationName: string;
  tags: string[];
  departments: Department[];
}

export interface Department {
  id: number;
  name: string;
  locationAddress: string[];
}
